#!/usr/bin/env python

import matplotlib.pyplot as plt
from mosaic import mosaic
import numpy as np
import os
import png
import ra
import sys

data = ra.read(sys.argv[1]).squeeze()
data = mosaic(abs(data))
#data = mosaic(np.angle(data))
print 'minimum: ', data.min()
print 'maximum: ', data.max()

if len(sys.argv) > 2 and sys.argv[2] == '-l':
    data = np.log(data)
elif len(sys.argv) > 2 and sys.argv[2] == '-s':
    data = np.sqrt(data)
a = data.min()
b = data.max()
if a == b:
    a = 0
data = (data - a) / (b - a)
data = data*255
data = data.astype('int')
print 'minimum: ', a
print 'maximum: ', b
#png.from_array(data, 'L').save('img.png')
f = open('img.png', 'wb')
nx, ny = data.shape
print data.shape
w = png.Writer(ny, nx, greyscale=True)
w.write(f, data)
f.close()

#plt.imshow(data, cmap='gray')
os.system('imgcat img.png')
#plt.colorbar()
#plt.show()
